# Permalinks
permalink:        pretty

# Setup
title:            Random Machinations
tagline:          'Going Through Life'
description:      'My personal blog - check out more on my <a href="http://www.randommachinations.com/about" target="_blank">About</a> page. Currently using <a href="https://github.com/poole/lanyon" target="_blank">Lanyon</a> a reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.randommachinations.com

author:
  name:           'Kapdaddy'
  url:            https://github.com/kapdaddy

paginate:         5

highlighter:      rouge

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/kapdaddy/Random-Machinations
